export const ActionTypes = {
    ADD_TASK: "ADD_TASK",
    REMOVE_TASK: "REMOVE_TASK",
    SET_TASKS: "SET_TASKS",
    SELECTED_TASK: "SELECTED_TASK",
    REMOVE_SELECTED_TASK: "REMOVE_SELECTED_TASK",
    ADD_LIST: "ADD_LIST",
    SET_LISTS: "SET_LISTS",
};